#pragma once

#include <cstdint>

namespace Calculator::Types {

enum class ErrorCode : std::uint8_t {
  ERROR_NONE = 0,
  ERROR_UNKNOWN_OPTION = 1,
  ERROR_INVALID_NUMBER = 2,
  ERROR_MISSING_FIRST_NUMBER = 3,
  ERROR_MISSING_SECOND_NUMBER = 4,
  ERROR_MISSING_OPERATION = 5,
  ERROR_INVALID_OPERATION = 6,
  ERROR_DIVISION_BY_ZERO = 7,
  ERROR_NEGATIVE_FACTORIAL = 8,
  ERROR_NEGATIVE_POWER = 9,
  ERROR_OVERFLOW = 10,
  ERROR_INVALID_JSON = 11,
  ERROR_STORAGE = 12,
};

} // namespace Calculator::Types