#pragma once

namespace Calculator::Types {
enum class ErrorCode {
  ERR_NONE = 0,
  ERR_UNKNOWN_OPTION = 1,
  ERR_INVALID_NUMBER = 2,
  ERR_MISSING_FIRST_NUMBER = 3,
  ERR_MISSING_SECOND_NUMBER = 4,
  ERR_MISSING_OPERATION = 5,
  ERR_INVALID_OPERATION = 6,
  ERR_DIVISION_BY_ZERO = 7,
  ERR_NEGATIVE_FACTORIAL = 8,
  ERR_NEGATIVE_POWER = 9,
  ERR_OVERFLOW = 10,
  ERR_INVALID_JSON = 11,
  ERR_STORAGE = 12
};
} // namespace Calculator::Types